version: '3'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.56.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "55681:55681" # ZPages for debugging
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.35
    ports:
      - "16686:16686" # Jaeger UI

  grafana:
    image: grafana/grafana:9.3.4
    ports:
      - "3000:3000"
    depends_on:
      - jaeger
      - prometheus
    environment:
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource